version: "2"
services:
  portal:
    build:
      context: ./
    volumes:
      - ./:/opt
    command:
      bash -c "useradd -m -s /bin/bash $USER || true && 
                cp -R /srv/indigo-python/ /opt/ && 
                chown -R $USER:$USER /opt/indigo-python/ && 
                /bin/su -s /bin/bash -c 'make html' $USER"
